grpc_port: ":14000"
http_port: ":14001"
mongo_db:
  url: "mongodb://admin:admin@localhost:27017"
  db_name: "identity-authen-api"
  collection: "authen-info"
redis_cache:
  address: "identity-authen-api"
  url: "localhost:6379"
grpc_conn:
  address: ":11000"
  timeout: 20s
  access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl9pbmZvIjp7ImF1dGhlbnRpY2F0aW9uX2RvbmUiOnRydWUsInN1YmplY3QiOiJzZXJ2aWNlOmNvbW1vbiIsImV4cCI6MzA1NDExMDAzNiwicm9sZSI6WyJhZG1pbiJdLCJwZXJtaXNzaW9uX2FsbCI6dHJ1ZX0sImV4cCI6MzA1NDExMDAzNn0.QEiyFLjGCkICxUn9tSDfnz3Z4xbqJc4hp743GrbPWwY"
key_jwt: "thteam47"
exp: 24h
totp_secret: "thteam47"
time_out_redis: 10s
time_request_id: 5m
time_email_otp: 5m
components:
  user-service:
    address: ":11000"
    timeout: 20s
    access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl9pbmZvIjp7ImF1dGhlbnRpY2F0aW9uX2RvbmUiOnRydWUsInN1YmplY3QiOiJzZXJ2aWNlOmNvbW1vbiIsImV4cCI6MzA1NDExMDAzNiwicm9sZSI6WyJhZG1pbiJdLCJwZXJtaXNzaW9uX2FsbCI6dHJ1ZX0sImV4cCI6MzA1NDExMDAzNn0.QEiyFLjGCkICxUn9tSDfnz3Z4xbqJc4hp743GrbPWwY"
  combined-data-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  key-public-user-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  key-public-use-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  key-public-item-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  result-card-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  phase3-two-part-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  phase4-two-part-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  process-data-survey-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  process-data-survey2-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  process-data-total-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  process-data-sumilor-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  process-data-rtb-repository:
    mongo-client-wrapper:
      url: "mongodb://admin:admin@localhost:27017/"
      database: "recommend-api"
  customer-service:
    address: ":12000"
    timeout: 20s
    access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl9pbmZvIjp7ImF1dGhlbnRpY2F0aW9uX2RvbmUiOnRydWUsInN1YmplY3QiOiJzZXJ2aWNlOmNvbW1vbiIsImV4cCI6MzA1NDExMDAzNiwicm9sZSI6WyJhZG1pbiJdLCJwZXJtaXNzaW9uX2FsbCI6dHJ1ZX0sImV4cCI6MzA1NDExMDAzNn0.QEiyFLjGCkICxUn9tSDfnz3Z4xbqJc4hp743GrbPWwY"
  survey-service:
    address: ":11000"
    timeout: 20s
    access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl9pbmZvIjp7ImF1dGhlbnRpY2F0aW9uX2RvbmUiOnRydWUsInN1YmplY3QiOiJzZXJ2aWNlOmNvbW1vbiIsImV4cCI6MzA1NDExMDAzNiwicm9sZSI6WyJhZG1pbiJdLCJwZXJtaXNzaW9uX2FsbCI6dHJ1ZX0sImV4cCI6MzA1NDExMDAzNn0.QEiyFLjGCkICxUn9tSDfnz3Z4xbqJc4hp743GrbPWwY"
  identity-service:
    address: ":10000"
    timeout: 20s
    access_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl9pbmZvIjp7ImF1dGhlbnRpY2F0aW9uX2RvbmUiOnRydWUsInN1YmplY3QiOiJzZXJ2aWNlOmNvbW1vbiIsImV4cCI6MzA1NDExMDAzNiwicm9sZSI6WyJhZG1pbiJdLCJwZXJtaXNzaW9uX2FsbCI6dHJ1ZX0sImV4cCI6MzA1NDExMDAzNn0.QEiyFLjGCkICxUn9tSDfnz3Z4xbqJc4hp743GrbPWwY"
